# Generated by Django 4.2.13 on 2026-06-18 14:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identity', '0002_alter_gender_name_alter_namecontext_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='identity',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='identityrelationship',
            unique_together={('identity', 'consumer', 'relationship_type')},
        ),
    ]
