# Generated by Django 4.2.13 on 2026-06-21 14:04

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('identity', '0003_identity_is_public_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='identityrelationship',
            unique_together={('identity', 'consumer')},
        ),
    ]
