# Generated by Django 4.2.13 on 2026-07-16 19:05

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('identity', '0004_alter_identityrelationship_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identityname',
            name='name_value',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=100)),
        ),
    ]
